services:
  mykafka1:
    image: mykafka
    container_name: mykafka1
    networks:
      KafkaClusterPractice:
    ports:
      - 19094:19094
    environment:
      KAFKA_LISTENERS: INTERNAL://:9092,EXTERNAL://:19094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://mykafka1:9092,EXTERNAL://43.203.166.170:19094
    volumes:
      - zookeeper_data_1:/root/kafka/zookeeper
      - kafka_data_1:/root/kafka/data
      - kafka_log_1:/root/kafka/logs
    command: [ "sh", "-c", "service ssh start; tail -f /dev/null" ]
  mykafka2:
    image: mykafka
    container_name: mykafka2
    networks:
      KafkaClusterPractice:
    ports:
      - 29094:29094
    environment:
      KAFKA_LISTENERS: INTERNAL://:9092,EXTERNAL://:29094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://mykafka1:9092,EXTERNAL://43.203.166.170:29094
    volumes:
      - zookeeper_data_2:/root/kafka/zookeeper
      - kafka_data_2:/root/kafka/data
      - kafka_log_2:/root/kafka/logs
    command: [ "sh", "-c", "service ssh start; tail -f /dev/null" ]
  mykafka3:
    image: mykafka
    container_name: mykafka3
    networks:
      KafkaClusterPractice:
    ports:
      - 39094:39094
    environment:
      KAFKA_LISTENERS: INTERNAL://:9092,EXTERNAL://:39094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://mykafka1:9092,EXTERNAL://43.203.166.170:39094
    volumes:
      - zookeeper_data_3:/root/kafka/zookeeper
      - kafka_data_3:/root/kafka/data
      - kafka_log_3:/root/kafka/logs
    command: [ "sh", "-c", "service ssh start; tail -f /dev/null" ]

volumes:
  zookeeper_data_1:
  kafka_data_1:
  kafka_log_1:
  zookeeper_data_2:
  kafka_data_2:
  kafka_log_2:
  zookeeper_data_3:
  kafka_data_3:
  kafka_log_3:


networks:
  KafkaClusterPractice: