apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: kafka-svc-domain
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: mykafka
          image: gnswp21/mykafka_k8s:latest
          ports:
            - containerPort: 9092
              name: broker
          command: [ "/bin/sh" ]
          args: [ "-c", "tail -f /dev/null" ]

