FROM ubuntu:22.04

WORKDIR /root

RUN apt-get update && \
    apt-get install -y openjdk-11-jdk && \
    apt-get install -y libasound2 nano && \
    apt-get clean

# Set JAVA_HOME environment variable
ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
ENV PATH $JAVA_HOME/bin:$PATH